/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.abf.module.jnl.entity;

import org.tis.tools.core.utils.StringUtil;

import java.io.Serializable;

/**
 * 
 * <pre>
 * 记录日志差异值
 * 模型文件 ： D:\tistools\tools-core-basic\model\jnl-mysql.erm
 * 业务域：jnl
 * 模型：LOG_ABF_CHANGE 记录日志差异值
 *
 * 记录日志差异值
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */

public class LogAbfChange implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "LOG_ABF_CHANGE" ; 
	/* LOG_ABF_CHANGE table's columns definition */
	/** GUID_HISTORY ：操作记录<br/><br/> */
	public static final String COLUMN_GUID_HISTORY = "guid_history" ; 
	/** CHANGE_KEY ：改变项键名<br/><br/> */
	public static final String COLUMN_CHANGE_KEY = "change_key" ; 
	/** CHANGE_VALUE ：改变项键值<br/><br/> */
	public static final String COLUMN_CHANGE_VALUE = "change_value" ; 
	/** 对应的类名 */
	public static final String CLASS_NAME = "org.tis.tools.model.po.jnl.LogAbfChange";
    /** GUID_HISTORY字段名<br/> */
    public static final String NAME_GUID_HISTORY = "操作记录" ;
    /** CHANGE_KEY字段名<br/> */
    public static final String NAME_CHANGE_KEY = "改变项键名" ;
    /** CHANGE_VALUE字段名<br/> */
    public static final String NAME_CHANGE_VALUE = "改变项键值" ;
	
	
	/** 字段类型：varchar<br/>字段名：操作记录<br/>描述： */
	private String guidHistory ;
	
	/** 字段类型：varchar<br/>字段名：改变项键名<br/>描述： */
	private String changeKey ;
	
	/** 字段类型：varchar<br/>字段名：改变项键值<br/>描述： */
	private String changeValue ;

	/**
	* Default Constructor
	*/
	public LogAbfChange() {
	}

	
	/**
	 * Set the 操作记录.
	 * 
	 * @param guidHistory
	 *            操作记录
	 */
	public void setGuidHistory(String guidHistory) {
 		this.guidHistory = guidHistory == null ? null : guidHistory.trim() ;
    }
    
    /**
	 * Get the 操作记录.
	 * 
	 * @return 操作记录
	 */
	public String getGuidHistory(){
		return this.guidHistory ;
    }
	
	/**
	 * Set the 改变项键名.
	 * 
	 * @param changeKey
	 *            改变项键名
	 */
	public void setChangeKey(String changeKey) {
 		this.changeKey = changeKey == null ? null : changeKey.trim() ;
    }
    
    /**
	 * Get the 改变项键名.
	 * 
	 * @return 改变项键名
	 */
	public String getChangeKey(){
		return this.changeKey ;
    }
	
	/**
	 * Set the 改变项键值.
	 * 
	 * @param changeValue
	 *            改变项键值
	 */
	public void setChangeValue(String changeValue) {
 		this.changeValue = changeValue == null ? null : changeValue.trim() ;
    }
    
    /**
	 * Get the 改变项键值.
	 * 
	 * @return 改变项键值
	 */
	public String getChangeValue(){
		return this.changeValue ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ;
	}
}