/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.abf.module.jnl.entity;

import org.tis.tools.core.utils.StringUtil;

import java.io.Serializable;

/**
 * 
 * <pre>
 * 记录关键值
 * 模型文件 ： D:\tistools\tools-core-basic\model\jnl-mysql.erm
 * 业务域：jnl
 * 模型：LOG_ABF_KEYWORD 记录关键值
 *
 * 记录关键值
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class LogAbfKeyword implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "LOG_ABF_KEYWORD" ; 
	/* LOG_ABF_KEYWORD table's columns definition */
	/** GUID_HISTORY ：操作记录<br/><br/> */
	public static final String COLUMN_GUID_HISTORY = "guid_history" ; 
	/** PARAM ：关键值名称<br/><br/> */
	public static final String COLUMN_PARAM = "param" ; 
	/** VALUE ：关键值<br/><br/> */
	public static final String COLUMN_VALUE = "value" ; 
	/** 对应的类名 */
	public static final String CLASS_NAME = "org.tis.tools.model.po.jnl.LogAbfKeyword";
    /** GUID_HISTORY字段名<br/> */
    public static final String NAME_GUID_HISTORY = "操作记录" ;
    /** PARAM字段名<br/> */
    public static final String NAME_PARAM = "关键值名称" ;
    /** VALUE字段名<br/> */
    public static final String NAME_VALUE = "关键值" ;
	
	
	/** 字段类型：varchar<br/>字段名：操作记录<br/>描述： */
	private String guidHistory ;
	
	/** 字段类型：varchar<br/>字段名：关键值名称<br/>描述： */
	private String param ;
	
	/** 字段类型：varchar<br/>字段名：关键值<br/>描述： */
	private String value ;

	/**
	* Default Constructor
	*/
	public LogAbfKeyword() {
	}

	
	/**
	 * Set the 操作记录.
	 * 
	 * @param guidHistory
	 *            操作记录
	 */
	public void setGuidHistory(String guidHistory) {
 		this.guidHistory = guidHistory == null ? null : guidHistory.trim() ;
    }
    
    /**
	 * Get the 操作记录.
	 * 
	 * @return 操作记录
	 */
	public String getGuidHistory(){
		return this.guidHistory ;
    }
	
	/**
	 * Set the 关键值名称.
	 * 
	 * @param param
	 *            关键值名称
	 */
	public void setParam(String param) {
 		this.param = param == null ? null : param.trim() ;
    }
    
    /**
	 * Get the 关键值名称.
	 * 
	 * @return 关键值名称
	 */
	public String getParam(){
		return this.param ;
    }
	
	/**
	 * Set the 关键值.
	 * 
	 * @param value
	 *            关键值
	 */
	public void setValue(String value) {
 		this.value = value == null ? null : value.trim() ;
    }
    
    /**
	 * Get the 关键值.
	 * 
	 * @return 关键值
	 */
	public String getValue(){
		return this.value ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ;
	}
}