/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.abf.module.jnl.entity;

import com.baomidou.mybatisplus.annotations.TableId;
import org.tis.tools.core.utils.StringUtil;

import java.io.Serializable;

/**
 * 
 * <pre>
 * 操作对象历史记录
 * 模型文件 ： D:\tistools\tools-core-basic\model\jnl-mysql.erm
 * 业务域：jnl
 * 模型：LOG_ABF_HISTORY 操作对象历史记录
 *
 * 记录客户与网点系统接触的所有日志明细，这些接触行为包括：
客户主动接触网点，如：使用自助设备；
柜员主动接触客户，如：厅堂经理介绍业务，高柜柜员为客户办理交易等；
客户间接接触网点，如：社区银行营销活动，客户通过商家积分兑换了银行理财优惠券；
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class LogAbfHistory implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "LOG_ABF_HISTORY" ; 
	/* LOG_ABF_HISTORY table's columns definition */
	/** GUID ：数据主键<br/><br/>全局唯一标识符（GUID，Globally Unique Identifier） */
	public static final String COLUMN_GUID = "guid" ; 
	/** GUID_OPERATE ：操作日志GUID<br/><br/> */
	public static final String COLUMN_GUID_OPERATE = "guid_operate" ; 
	/** OBJ_FROM ：对象来源<br/><br/> */
	public static final String COLUMN_OBJ_FROM = "obj_from" ; 
	/** OBJ_TYPE ：对象类型<br/><br/> */
	public static final String COLUMN_OBJ_TYPE = "obj_type" ; 
	/** OBJ_GUID ：对象GUID<br/><br/> */
	public static final String COLUMN_OBJ_GUID = "obj_guid" ; 
	/** OBJ_NAME ：对象名<br/><br/> */
	public static final String COLUMN_OBJ_NAME = "obj_name" ; 
	/** OBJ_VALUE ：对象值<br/><br/> */
	public static final String COLUMN_OBJ_VALUE = "obj_value" ; 
	/** 对应的类名 */
	public static final String CLASS_NAME = "org.tis.tools.model.po.jnl.LogAbfHistory";
    /** GUID字段名<br/> */
    public static final String NAME_GUID = "数据主键" ;
    /** GUID_OPERATE字段名<br/> */
    public static final String NAME_GUID_OPERATE = "操作日志GUID" ;
    /** OBJ_FROM字段名<br/> */
    public static final String NAME_OBJ_FROM = "对象来源" ;
    /** OBJ_TYPE字段名<br/> */
    public static final String NAME_OBJ_TYPE = "对象类型" ;
    /** OBJ_GUID字段名<br/> */
    public static final String NAME_OBJ_GUID = "对象GUID" ;
    /** OBJ_NAME字段名<br/> */
    public static final String NAME_OBJ_NAME = "对象名" ;
    /** OBJ_VALUE字段名<br/> */
    public static final String NAME_OBJ_VALUE = "对象值" ;
	
	@TableId
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：全局唯一标识符（GUID，Globally Unique Identifier） */
	private String guid ;
	
	/** 字段类型：varchar<br/>字段名：操作日志GUID<br/>描述： */
	private String guidOperate ;
	
	/** 字段类型：varchar<br/>字段名：对象来源<br/>描述： */
	private String objFrom ;
	
	/** 字段类型：varchar<br/>字段名：对象类型<br/>描述： */
	private String objType ;
	
	/** 字段类型：varchar<br/>字段名：对象GUID<br/>描述： */
	private String objGuid ;
	
	/** 字段类型：varchar<br/>字段名：对象名<br/>描述： */
	private String objName ;
	
	/** 字段类型：varchar<br/>字段名：对象值<br/>描述： */
	private String objValue ;

	/**
	* Default Constructor
	*/
	public LogAbfHistory() {
	}

	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
 		this.guid = guid == null ? null : guid.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid(){
		return this.guid ;
    }
	
	/**
	 * Set the 操作日志GUID.
	 * 
	 * @param guidOperate
	 *            操作日志GUID
	 */
	public void setGuidOperate(String guidOperate) {
 		this.guidOperate = guidOperate == null ? null : guidOperate.trim() ;
    }
    
    /**
	 * Get the 操作日志GUID.
	 * 
	 * @return 操作日志GUID
	 */
	public String getGuidOperate(){
		return this.guidOperate ;
    }
	
	/**
	 * Set the 对象来源.
	 * 
	 * @param objFrom
	 *            对象来源
	 */
	public void setObjFrom(String objFrom) {
 		this.objFrom = objFrom == null ? null : objFrom.trim() ;
    }
    
    /**
	 * Get the 对象来源.
	 * 
	 * @return 对象来源
	 */
	public String getObjFrom(){
		return this.objFrom ;
    }
	
	/**
	 * Set the 对象类型.
	 * 
	 * @param objType
	 *            对象类型
	 */
	public void setObjType(String objType) {
 		this.objType = objType == null ? null : objType.trim() ;
    }
    
    /**
	 * Get the 对象类型.
	 * 
	 * @return 对象类型
	 */
	public String getObjType(){
		return this.objType ;
    }
	
	/**
	 * Set the 对象GUID.
	 * 
	 * @param objGuid
	 *            对象GUID
	 */
	public void setObjGuid(String objGuid) {
 		this.objGuid = objGuid == null ? null : objGuid.trim() ;
    }
    
    /**
	 * Get the 对象GUID.
	 * 
	 * @return 对象GUID
	 */
	public String getObjGuid(){
		return this.objGuid ;
    }
	
	/**
	 * Set the 对象名.
	 * 
	 * @param objName
	 *            对象名
	 */
	public void setObjName(String objName) {
 		this.objName = objName == null ? null : objName.trim() ;
    }
    
    /**
	 * Get the 对象名.
	 * 
	 * @return 对象名
	 */
	public String getObjName(){
		return this.objName ;
    }
	
	/**
	 * Set the 对象值.
	 * 
	 * @param objValue
	 *            对象值
	 */
	public void setObjValue(String objValue) {
 		this.objValue = objValue == null ? null : objValue.trim() ;
    }
    
    /**
	 * Get the 对象值.
	 * 
	 * @return 对象值
	 */
	public String getObjValue(){
		return this.objValue ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ;
	}
}