/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.abf.module.om.entity;

import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.SerializerFeature;
import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.annotations.Version;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.tis.tools.abf.module.common.entity.enums.YON;
import org.tis.tools.abf.module.om.entity.enums.OmOrgStatus;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 
 * <pre>
 * 机构信息表
 * 模型文件 ： D:\tistools\tools-core-basic\model\ABF-mysql.erm
 * 业务域：om
 * 模型：OM_ORG 机构信息表
 *
 * 机构部门（Organization）表
允许定义多个平行机构
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("om_org")
public class OmOrg extends Model<OmOrg> {

	/**
	 * 主键值
	 */
	@Override
	protected Serializable pkVal() {
		return this.guid;
	}
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "OM_ORG" ; 
	/* OM_ORG table's columns definition */
	/** GUID ：数据主键<br/><br/>全局唯一标识符（GUID，Globally Unique Identifier），系统自动生成； */
	public static final String COLUMN_GUID = "guid" ; 
	/** ORG_CODE ：机构代码<br/><br/>业务上对机构实体的编码。 一般根据机构等级和机构类型进行有规则的编码。 */
	public static final String COLUMN_ORG_CODE = "org_code" ; 
	/** ORG_NAME ：机构名称<br/><br/> */
	public static final String COLUMN_ORG_NAME = "org_name" ; 
	/** ORG_TYPE ：机构类型<br/><br/>见业务字典： DICT_OM_ORGTYPE 如：总公司/总部部门/分公司/分公司部门... */
	public static final String COLUMN_ORG_TYPE = "org_type" ; 
	/** ORG_DEGREE ：机构等级<br/><br/>见业务字典： DICT_OM_ORGDEGREE 如：总行，分行，海外分行... */
	public static final String COLUMN_ORG_DEGREE = "org_degree" ; 
	/** ORG_STATUS ：机构状态<br/><br/>见业务字典： DICT_OM_ORGSTATUS */
	public static final String COLUMN_ORG_STATUS = "org_status" ; 
	/** ORG_LEVEL ：机构层次<br/><br/> */
	public static final String COLUMN_ORG_LEVEL = "org_level" ; 
	/** GUID_PARENTS ：父机构GUID<br/><br/> */
	public static final String COLUMN_GUID_PARENTS = "guid_parents" ; 
	/** ORG_SEQ ：机构序列<br/><br/>类似面包屑导航，以“.”分割所有父机构GUID，明确示意出本机构所处层级归属 格式： 父机构GUID.父机构GUID....本机构GUID */
	public static final String COLUMN_ORG_SEQ = "org_seq" ; 
	/** ORG_ADDR ：机构地址<br/><br/> */
	public static final String COLUMN_ORG_ADDR = "org_addr" ; 
	/** ZIPCODE ：邮编<br/><br/>见业务字典： DICT_SD_ZIPCODE */
	public static final String COLUMN_ZIPCODE = "zipcode" ;
	/** LINK_MAN ：联系人姓名<br/><br/> */
	public static final String COLUMN_LINK_MAN = "link_man" ; 
	/** LINK_TEL ：联系电话<br/><br/> */
	public static final String COLUMN_LINK_TEL = "link_tel" ; 
	/** EMAIL ：电子邮件<br/><br/> */
	public static final String COLUMN_EMAIL = "email" ;
	/** START_DATE ：生效日期<br/><br/> */
	public static final String COLUMN_START_DATE = "start_date" ; 
	/** END_DATE ：失效日期<br/><br/> */
	public static final String COLUMN_END_DATE = "end_date" ; 
	/** AREA ：所属地域<br/><br/>见业务字典： DICT_SD_AREA */
	public static final String COLUMN_AREA = "area" ; 
	/** CREATE_TIME ：创建时间<br/><br/> */
	public static final String COLUMN_CREATE_TIME = "create_time" ; 
	/** LAST_UPDATE ：最近更新时间<br/><br/> */
	public static final String COLUMN_LAST_UPDATE = "last_update" ; 
	/** UPDATOR ：最近更新人员<br/><br/> */
	public static final String COLUMN_UPDATOR = "updator" ; 
	/** SORT_NO ：排列顺序编号<br/><br/>维护时，可手工指定从0开始的自然数字；如果为空，系统将按照机构代码排序。 */
	public static final String COLUMN_SORT_NO = "sort_no" ; 
	/** ISLEAF ：是否叶子节点<br/><br/>系统根据当前是否有下级机构判断更新（见业务字典 DICT_YON） */
	public static final String COLUMN_ISLEAF = "isleaf" ; 
	/** SUB_COUNT ：子节点数<br/><br/>维护时系统根据当前拥有子机构／部分数实时更新 */
	public static final String COLUMN_SUB_COUNT = "sub_count" ; 
	/** REMARK ：备注<br/><br/> */
	public static final String COLUMN_REMARK = "remark" ; 
	/** 对应的类名 */
	public static final String CLASS_NAME = "org.tis.tools.model.po.om.OmOrg";
    /** GUID字段名<br/> */
    public static final String NAME_GUID = "数据主键" ;
    /** ORG_CODE字段名<br/> */
    public static final String NAME_ORG_CODE = "机构代码" ;
    /** ORG_NAME字段名<br/> */
    public static final String NAME_ORG_NAME = "机构名称" ;
    /** ORG_TYPE字段名<br/> */
    public static final String NAME_ORG_TYPE = "机构类型" ;
    /** ORG_DEGREE字段名<br/> */
    public static final String NAME_ORG_DEGREE = "机构等级" ;
    /** ORG_STATUS字段名<br/> */
    public static final String NAME_ORG_STATUS = "机构状态" ;
    /** GUID_PARENTS字段名<br/> */
    public static final String NAME_GUID_PARENTS = "父机构GUID" ;
    /** ORG_SEQ字段名<br/> */
    public static final String NAME_ORG_SEQ = "机构序列" ;
    /** ORG_ADDR字段名<br/> */
    public static final String NAME_ORG_ADDR = "机构地址" ;
    /** LINK_MAN字段名<br/> */
    public static final String NAME_LINK_MAN = "联系人姓名" ;
    /** LINK_TEL字段名<br/> */
    public static final String NAME_LINK_TEL = "联系电话" ;
    /** START_DATE字段名<br/> */
    public static final String NAME_START_DATE = "生效日期" ;
    /** END_DATE字段名<br/> */
    public static final String NAME_END_DATE = "失效日期" ;
    /** AREA字段名<br/> */
    public static final String NAME_AREA = "所属地域" ;
    /** CREATE_TIME字段名<br/> */
    public static final String NAME_CREATE_TIME = "创建时间" ;
    /** LAST_UPDATE字段名<br/> */
    public static final String NAME_LAST_UPDATE = "最近更新时间" ;
    /** UPDATOR字段名<br/> */
    public static final String NAME_UPDATOR = "最近更新人员" ;
    /** SORT_NO字段名<br/> */
    public static final String NAME_SORT_NO = "排列顺序编号" ;
    /** ISLEAF字段名<br/> */
    public static final String NAME_ISLEAF = "是否叶子节点" ;
	 /** REMARK字段名<br/> */
	public static final String NAME_REMARK = "备注" ;

	@TableId
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：全局唯一标识符（GUID，Globally Unique Identifier），系统自动生成； */
	private String guid ;

	/** 字段类型：varchar<br/>字段名：机构代码<br/>描述：业务上对机构实体的编码。 一般根据机构等级和机构类型进行有规则的编码。 */
	private String orgCode ;

	/** 字段类型：varchar<br/>字段名：机构名称<br/>描述： */
	private String orgName ;

	/** 字段类型：varchar<br/>字段名：机构类型<br/>描述：见业务字典： DICT_OM_ORGTYPE 如：总公司/总部部门/分公司/分公司部门... */
	private String orgType ;

	/** 字段类型：varchar<br/>字段名：机构等级<br/>描述：见业务字典： DICT_OM_ORGDEGREE 如：总行，分行，海外分行... */
	private String orgDegree ;

	@JSONField(serialzeFeatures= SerializerFeature.WriteEnumUsingToString)
	/** 字段类型：varchar<br/>字段名：机构状态<br/>描述：见业务字典： DICT_OM_ORGSTATUS */
	private OmOrgStatus orgStatus ;

	/** 字段类型：varchar<br/>字段名：父机构GUID<br/>描述： */
	private String guidParents ;

	/** 字段类型：varchar<br/>字段名：机构序列<br/>描述：类似面包屑导航，以“.”分割所有父机构GUID，明确示意出本机构所处层级归属 格式： 父机构GUID.父机构GUID....本机构GUID */
	private String orgSeq ;

	/** 字段类型：varchar<br/>字段名：机构地址<br/>描述： */
	private String orgAddr ;

	/** 字段类型：varchar<br/>字段名：联系人姓名<br/>描述： */
	private String linkMan ;

	/** 字段类型：varchar<br/>字段名：联系电话<br/>描述： */
	private String linkTel ;

	/** 字段类型：date<br/>字段名：生效日期<br/>描述： */
	private Date startDate ;

	/** 字段类型：date<br/>字段名：失效日期<br/>描述： */
	private Date endDate ;

	/** 字段类型：varchar<br/>字段名：所属地域<br/>描述：见业务字典： DICT_SD_AREA */
	private String area ;

	/** 字段类型：timestamp<br/>字段名：创建时间<br/>描述： */
	private Date createTime ;

	@Version
	/** 字段类型：timestamp<br/>字段名：最近更新时间<br/>描述： */
	private Date lastUpdate ;

	/** 字段类型：varchar<br/>字段名：最近更新人员<br/>描述： */
	private String updator ;

	/** 字段类型：decimal<br/>字段名：排列顺序编号<br/>描述：维护时，可手工指定从0开始的自然数字；如果为空，系统将按照机构代码排序。 */
	private BigDecimal sortNo ;

	/** 字段类型：char<br/>字段名：是否叶子节点<br/>描述：系统根据当前是否有下级机构判断更新（见业务字典 DICT_YON） */
	@JSONField(serialzeFeatures= SerializerFeature.WriteEnumUsingToString)
	private YON isleaf ;

	/** 字段类型：varchar<br/>字段名：备注<br/>描述： */
	private String remark ;

}